//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examuser
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class carinfo
    {
        public int car_id { get; set; }

        [Display(Name = "Марка")]
        public string mark { get; set; }
        [Display(Name = "Название")]
        public string cartitle { get; set; }
        [Display(Name = "Модель")]
        public string model { get; set; }
        [Display(Name = "Photo")]
        public string imgpath { get; set; }

        [Display(Name = "Лошадиных сил")]
        public int hwp { get; set; }
        [Display(Name = "Описание")]
        public string cardescr { get; set; }
    }
}
